services:
  db:
    container_name: mariadb
    build:
      dockerfile: ./mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-network

  wordpress:
    container_name: wordpress
    build:
      dockerfile: ./wordpress/Dockerfile
    volumes:
      - wp_data:/var/www/html
      - ./wordpress:/tmp/wp-config
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_AUTO_UPDATE_CORE', false);
        define('AUTOMATIC_UPDATER_DISABLED', true);
      WORDPRESS_TITLE: "cloud-1 by abied-ch"
      WORDPRESS_ADMIN_USER: admin 
      WORDPRESS_ADMIN_PASSWORD: password 
      WORDPRESS_ADMIN_EMAIL: abied-ch@student.42vienna.com 
      WORDPRESS_URL: "http://localhost:8080"
    depends_on:
      - db
    networks:
      - wp-network
    # entrypoint: [ "sh", "/tmp/wp-config/entrypoint.sh" ]

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - wp-network

volumes:
  db_data:
  wp_data:

networks:
  wp-network:
