services:
  nginx:
    build: services/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/ubuntu/data/web:/var/www/html
    networks:
      - cloud-1
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: services/wordpress/
    container_name: wordpress
    volumes:
      - /home/abied-ch/data/web:/var/www/html
    networks:
      - cloud-1
    env_file:
      - .env
    depends_on: 
      mariadb:
        condition: service_healthy
    restart: always
  mariadb:
    build: services/mariadb/
    container_name: mariadb
    volumes:
      - /home/abied-ch/data/database:/var/lib/mysql
    networks:
      - cloud-1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$DB_ADMIN_PWD"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

networks:
  cloud-1:
    driver:
      bridge
