
- name: Print domain name
  debug:
    msg: "domain: |{{ domain }}|"
- name: update apt cache
  apt:
    update_cache: yes

- name: install packages
  apt:
    name:
      - curl
      - git
      - unzip
    state: present
