- name: copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/ubuntu/compose.yaml

- name: copy .env
  copy:
    src: ../../../.env
    dest: /home/ubuntu/.env

- name: start Docker containers
  command: docker compose up -d
  args:
    chdir: /home/ubuntu

- name: waiting
  command: sleep 10

- name: Get the current IP address
  set_fact:
    current_ip: "{{ ansible_default_ipv4.address }}"

- name: Install WordPress via cli
  shell: |
    docker exec $(docker ps --filter "ancestor=wordpress:latest" --format "{{ '{{' }}.ID{{ '}}' }}") /bin/bash -c "
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && 
    chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp-cli && 
    wp-cli core install --allow-root --url={{ current_ip }} --title=cloud-1 --admin_user=admin --admin_password={{ wp_admin_password }} --admin_email=admin@admin.com"