- name: copy docker-compose.yml
  copy:
    src: ../../../compose.yaml
    dest: /home/ubuntu/compose.yaml
    
- name: copy init_wp.sh script
  copy:
    src: ../../../init_wp.sh
    dest: /home/ubuntu/init_wp.sh
    mode: 0777

- name: start Docker containers
  command: docker compose up -d
  args:
    chdir: /home/ubuntu

- name: waiting
  command: sleep 10

- name: Install wp-cli and WordPress
  shell: docker exec $(docker ps --filter "ancestor=wordpress:latest" --format "{{ '{{' }}.ID{{ '}}' }}") /bin/bash -c "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp-cli && wp-cli core install --allow-root --url=188.245.104.21 --title=another --admin_user=goos --admin_password=goos --admin_email=test@test.com"
