- name: install Nginx
  apt:
    name: nginx
    state: present

- name: install Certbot for TLS
  apt:
    name: 
      - certbot
      - python3-certbot-nginx
    state: present

- name: Add SSH to ufw allowed
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '22'

- name: Add HTTP to ufw allowed
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '80'

- name: Add HTTPS to ufw allowed
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '443'

- name: ufw enable
  community.general.ufw:
    state: enabled
    policy: deny 

- name: check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert_file

- name: obtain SSL certifcate with Certbot
  shell: certbot certonly --nginx -d {{ domain }} --non-interactive --agree-tos --email abied-ch@student.42vienna.com
  when: not cert_file.stat.exists

- name: SSL certificate auto-renewal
  cron:
    name: "certbot renewal"
    job: "certbot renew --quiet"
    special_time: daily

- name: copy Nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress
  notify: Restart Nginx

- name: enable Nginx site
  file:
    src: /etc/nginx/sites-available/wordpress
    dest: /etc/nginx/sites-enabled/wordpress
    state: link
  notify: Restart Nginx

- name: remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx