- name: install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present

- name: add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: add "{{ ansible_user }}" user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: add docker to autostart
  command: sudo systemctl enable docker